'use client';

import { Activity, Bell, CheckCircle2, FileText, FolderOpen, ShieldCheck, SlidersHorizontal, UploadCloud, UserRound } from 'lucide-react';
import type { VoiceAccent } from '@/types';
import type { WorkspaceSection } from '@/components/layout/app-sidebar';

type WorkspaceUser = { firstName: string; email: string };

export function WorkspaceView({ section, user, accent, onAccentChange }: { section: WorkspaceSection; user: WorkspaceUser; accent: VoiceAccent; onAccentChange: (accent: VoiceAccent) => void }) {
  if (section === 'Dashboard') return <div className="workspace-view"><div className="workspace-heading"><div><p className="workspace-eyebrow">Workspace overview</p><h1>Good morning, {user.firstName || 'User'}.</h1><p>Keep track of your assistant activity and operational priorities.</p></div><button className="workspace-action"><Bell className="h-4 w-4" /> Notifications</button></div><div className="workspace-stat-grid"><div className="workspace-stat"><span>Open requests</span><strong>12</strong><small><Activity className="h-3.5 w-3.5 text-emerald-500" /> 8% from last week</small></div><div className="workspace-stat"><span>Completed this month</span><strong>48</strong><small><CheckCircle2 className="h-3.5 w-3.5 text-sky-500" /> On track</small></div><div className="workspace-stat"><span>Assistant availability</span><strong>99.9%</strong><small><ShieldCheck className="h-3.5 w-3.5 text-emerald-500" /> All systems operational</small></div></div><div className="workspace-card"><div className="workspace-card-title"><div><p className="workspace-eyebrow">Recent activity</p><h2>What needs your attention</h2></div><button className="workspace-link">View activity →</button></div><div className="workspace-activity"><div><CheckCircle2 /><span><strong>Leave request processed</strong><small>Sarah Jenkins · 12 minutes ago</small></span><em>Completed</em></div><div><FileText /><span><strong>Expense report ready for review</strong><small>Acme Corp dinner · Yesterday</small></span><em className="pending">Review</em></div><div><ShieldCheck /><span><strong>Microsoft connection verified</strong><small>Identity and access · Yesterday</small></span><em>Secure</em></div></div></div></div>;
  if (section === 'Files') return <div className="workspace-view"><div className="workspace-heading"><div><p className="workspace-eyebrow">Knowledge workspace</p><h1>Files</h1><p>Keep the documents your assistant uses in one secure place.</p></div><label className="workspace-action workspace-upload"><UploadCloud className="h-4 w-4" /> Upload file<input type="file" className="sr-only" /></label></div><div className="workspace-card"><div className="workspace-card-title"><div><p className="workspace-eyebrow">Your library</p><h2>Recent documents</h2></div><FolderOpen className="h-5 w-5 text-slate-400" /></div><div className="workspace-file-list"><div><FileText /><span><strong>Operations handbook.pdf</strong><small>PDF · Updated today</small></span><button>Open</button></div><div><FileText /><span><strong>FY26 expense policy.docx</strong><small>DOCX · Updated yesterday</small></span><button>Open</button></div><div><FileText /><span><strong>Team leave calendar.xlsx</strong><small>XLSX · Updated May 16</small></span><button>Open</button></div></div></div></div>;
  return <div className="workspace-view"><div className="workspace-heading"><div><p className="workspace-eyebrow">Workspace preferences</p><h1>Settings</h1><p>Manage how Ashistanto works for you.</p></div><SlidersHorizontal className="h-6 w-6 text-slate-400" /></div><div className="workspace-card settings-card"><div className="settings-row"><div><strong>Voice language</strong><p>Choose the accent used for voice conversations.</p></div><select value={accent} onChange={(event) => onAccentChange(event.target.value as VoiceAccent)}><option value="american">English (US)</option><option value="british">English (UK)</option><option value="japanese">日本語</option></select></div><div className="settings-row"><div><strong>Connected account</strong><p>{user.email || 'Preview mode — sign in with Microsoft to connect your account.'}</p></div><UserRound className="h-5 w-5 text-slate-400" /></div><div className="settings-row"><div><strong>Security</strong><p>Your conversations are protected by the configured enterprise session.</p></div><ShieldCheck className="h-5 w-5 text-emerald-500" /></div></div></div>;
}